spring:
  profiles:
    active: dev

  datasource:
    houhe:
      url: jdbc:mysql://192.168.0.181:3306/houhe_test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
      username: root
      password: 123456


  session:
    store-type: none

  aop:
    auto: true

logging:
  config: classpath:logback.xml
#logging:
#  path: /workspace/rock/jpa-test/log
